library:
  source-dirs: src
tests:
  haskell-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell
copyright: 2020 Author name here
maintainer: example@example.com
dependencies:
- mtl
- base
- base >= 4.7 && < 5
- threepenny-gui
- split
- regex-posix
- time
- random
- mtl
name: haskell
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/haskell
license: BSD3
executables:
  haskell-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell
description: Please see the README on GitHub at <https://github.com/githubuser/haskell#readme>
